<?php
$sites = array(
array('name' => 'alltagz', 'icon' => 69, 'url' => 'http://www.alltagz.de', 'share-link' => 'http://www.alltagz.de/bookmarks/?action=add&amp;address=<url>&amp;title=<title>'),
array('name' => 'Allvoices', 'icon' => 75, 'url' => 'http://www.allvoices.com', 'share-link' => 'http://www.allvoices.com/post_event?url=<url>&amp;title=<title>'),
array('name' => 'myAOL', 'icon' => 2, 'url' => 'http://favorites.my.aol.com', 'share-link' => 'http://favorites.my.aol.com/ffclient/webroot/0.4.1/src/html/addBookmarkDialog.html?url=<url>&amp;title=<title>&amp;favelet=true'),
array('name' => 'Arto', 'icon' => 76, 'url' => 'http://www.arto.com', 'share-link' => 'http://www.arto.com/section/linkshare/?lu=<url>&amp;ln=<title>'),
array('name' => 'Ask', 'icon' => 3, 'url' => 'http://myjeeves.ask.com', 'share-link' => 'http://myjeeves.ask.com/mysearch/BookmarkIt?v=1.2&amp;t=webpages&amp;url=<url>&amp;title=<title>'),
array('name' => 'Backflip', 'icon' => 62, 'url' => 'http://www.backflip.com', 'share-link' => 'http://www.backflip.com/add_page_pop.ihtml?url=<url>&amp;title=<title>'),
array('name' => 'BallHype', 'icon' => 63, 'url' => 'http://ballhype.com', 'share-link' => 'http://ballhype.com/post/url/?url=<url>&amp;title=<title>'),
array('name' => 'Bebo', 'icon' => 64, 'url' => 'http://bebo.com', 'share-link' => 'http://bebo.com/c/share?Url=<url>&amp;Title=<title>'),
array('name' => 'BibSonomy', 'icon' => 77, 'url' => 'http://www.bibsonomy.org', 'share-link' => 'http://www.bibsonomy.org/BibtexHandler?requTask=upload&amp;url=<url>&amp;description=<title>'),
array('name' => 'BlinkList', 'icon' => 4, 'url' => 'http://www.blinklist.com', 'share-link' => 'http://www.blinklist.com/index.php?Action=Blink/addblink.php&amp;Url=<url>&amp;Title=<title>'),
array('name' => 'Bloglines', 'icon' => 48, 'url' => 'http://www.bloglines.com', 'share-link' => 'http://www.bloglines.com/sub/<url>'),
array('name' => 'Blogmarks', 'icon' => 5, 'url' => 'http://blogmarks.net', 'share-link' => 'http://blogmarks.net/my/new.php?mini=1&amp;simple=1&amp;url=<url>&amp;title=<title>'),
array('name' => 'bookmark.it', 'icon' => 71, 'url' => 'http://www.bookmark.it', 'share-link' => 'http://www.bookmark.it/bookmark.php?url=<url>'),
array('name' => 'bookmarks.fr', 'icon' => 78, 'url' => 'http://www.bookmarks.fr', 'share-link' => 'http://www.bookmarks.fr/favoris/AjoutFavori?action=add&amp;address=<url>&amp;title=<title>'),
array('name' => 'BuddyMarks', 'icon' => 79, 'url' => 'http://buddymarks.com', 'share-link' => 'http://buddymarks.com/add_bookmark.php?bookmark_url=<url>&amp;bookmark_title=<title>'),
array('name' => 'Business Exchange', 'icon' => 73, 'url' => 'http://bx.businessweek.com', 'share-link' => 'http://bx.businessweek.com/api/add-article-to-bx.tn?url=<url>'),
array('name' => 'Bzzster', 'icon' => 80, 'url' => 'http://bzzster.com', 'share-link' => 'http://bzzster.com/share?v=5;link=<url>&amp;subject=<title>'),
array('name' => 'Care2', 'icon' => 6, 'url' => 'http://www.care2.com', 'share-link' => 'http://www.care2.com/news/news_post.html?url=<url>&amp;title=<title>'),
array('name' => 'citeulike', 'icon' => 81, 'url' => 'http://www.citeulike.org', 'share-link' => 'http://www.citeulike.org/posturl?url=<url>&amp;title=<title>'),
array('name' => 'Connotea', 'icon' => 82, 'url' => 'http://www.connotea.org', 'share-link' => 'http://www.connotea.org/add?uri=<url>&amp;title=<title>'),
array('name' => 'Current', 'icon' => 49, 'url' => 'http://current.com', 'share-link' => 'http://current.com/clipper.htm?url=<url>&amp;title=<title>'),
array('name' => 'deals plus', 'icon' => 74, 'url' => 'http://dealspl.us', 'share-link' => 'http://dealspl.us/add.php?ibm=1&amp;url=<url>'),
array('name' => 'del.icio.us', 'icon' => 7, 'url' => 'http://del.icio.us', 'share-link' => 'http://del.icio.us/post?url=<url>&amp;title=<title>'),
array('name' => 'Design Float', 'icon' => 50, 'url' => 'http://www.designfloat.com', 'share-link' => 'http://www.designfloat.com/submit.php?url=<url>&amp;title=<title>'),
array('name' => 'Digg', 'icon' => 8, 'url' => 'http://digg.com', 'share-link' => 'http://digg.com/submit?phase=2&amp;url=<url>&amp;title=<title>'),
array('name' => 'Diigo', 'icon' => 9, 'url' => 'http://www.diigo.com', 'share-link' => 'http://www.diigo.com/post?url=<url>&amp;title=<title>'),
array('name' => 'DZone', 'icon' => 10, 'url' => 'http://www.dzone.com', 'share-link' => 'http://www.dzone.com/links/add.html?url=<url>&amp;title=<title>'),
array('name' => 'Evernote', 'icon' => 83, 'url' => 'http://www.evernote.com', 'share-link' => 'http://www.evernote.com/clip.action?url=<url>&amp;title=<title>'),
array('name' => 'Expression', 'icon' => 84, 'url' => 'http://social.expression.microsoft.com', 'share-link' => 'http://social.expression.microsoft.com/en-US/action/Create/s/E/?url=<url>&amp;bm=true&amp;ttl=<title>'),
array('name' => 'Facebook', 'icon' => 11, 'url' => 'http://www.facebook.com', 'share-link' => 'http://www.facebook.com/sharer.php?u=<url>&amp;t=<title>'),
array('name' => 'Fark', 'icon' => 12, 'url' => 'http://www.fark.com', 'share-link' => 'http://cgi.fark.com/cgi/fark/submit.pl?new_url=<url>&amp;new_comment=<title>'),
array('name' => 'Faves', 'icon' => 13, 'url' => 'http://faves.com', 'share-link' => 'http://faves.com/Authoring.aspx?u=<url>&amp;t=<title>'),
array('name' => 'Feed Me Links', 'icon' => 14, 'url' => 'http://feedmelinks.com', 'share-link' => 'http://feedmelinks.com/categorize?from=toolbar&amp;op=submit&amp;url=<url>&amp;name=<title>'),
array('name' => 'Folkd', 'icon' => 85, 'url' => 'http://www.folkd.co', 'share-link' => 'http://www.folkd.com/submit/<url>'),
array('name' => 'FoxieWire', 'icon' => 86, 'url' => 'http://www.foxiewire.com', 'share-link' => 'http://www.foxiewire.com/submit?url=<url>&amp;title=<title>'),
array('name' => 'Fresqui', 'icon' => 51, 'url' => 'http://ocio.fresqui.com', 'share-link' => 'http://ocio.fresqui.com/post?url=<url>&amp;title=<title>'),
array('name' => 'FriendFeed', 'icon' => 52, 'url' => 'http://friendfeed.com', 'share-link' => 'http://friendfeed.com/share?url=<url>&amp;title=<title>'),
array('name' => 'funP', 'icon' => 53, 'url' => 'http://funp.com', 'share-link' => 'http://funp.com/pages/submit/add.php?url=<url>&amp;title=<title>'),
array('name' => 'Furl', 'icon' => 15, 'url' => 'http://www.furl.net', 'share-link' => 'http://www.furl.net/storeIt.jsp?u=<url>&amp;t=<title>'),
array('name' => 'Gabbr', 'icon' => 87, 'url' => 'http://www.gabbr.com', 'share-link' => 'http://www.gabbr.com/submit/?bookurl=<url>'),
array('name' => 'Global Grind', 'icon' => 88, 'url' => 'http://globalgrind.com', 'share-link' => 'http://globalgrind.com/submission/submit.aspx?url=<url>&amp;type=Article&amp;title=<title>'),
array('name' => 'Google', 'icon' => 16, 'url' => 'http://www.google.com', 'share-link' => 'http://www.google.com/bookmarks/mark?op=edit&amp;bkmk=<url>&amp;title=<title>'),
array('name' => 'Gravee', 'icon' => 89, 'url' => 'http://www.gravee.com', 'share-link' => 'http://www.gravee.com/account/bookmarkpop?u=<url>&amp;t=<title>'),
array('name' => 'HealthRanker', 'icon' => 90, 'url' => 'http://www.healthranker.com', 'share-link' => 'http://www.healthranker.com/submit.php?url=<url>&amp;title=<title>'),
array('name' => 'HEMiDEMi', 'icon' => 91, 'url' => 'http://www.hemidemi.com', 'share-link' => 'http://www.hemidemi.com/user_bookmark/new?url=<url>&amp;title=<title>'),
array('name' => 'Hugg', 'icon' => 17, 'url' => 'http://www.hugg.com', 'share-link' => 'http://www.hugg.com/submit?url=<url>'),
array('name' => 'identi.ca', 'icon' => 92, 'url' => 'http://identi.ca', 'share-link' => 'http://identi.ca/notice/new?status_textarea=<title>%20<url>'),
array('name' => 'Imera', 'icon' => 93, 'url' => 'http://www.imera.com.br', 'share-link' => 'http://www.imera.com.br/post_d.html?linkUrl=<url>&amp;linkName=<title>'),
array('name' => 'Instapaper', 'icon' => 94, 'url' => 'http://www.instapaper.com', 'share-link' => 'http://www.instapaper.com/b?u=<url>&amp;t={y}'),
array('name' => 'Jamespot', 'icon' => 95, 'url' => 'http://www.jamespot.com', 'share-link' => 'http://www.jamespot.com/?action=spotit&amp;url=<url>'),
array('name' => 'Jumptags', 'icon' => 96, 'url' => 'http://www.jumptags.com', 'share-link' => 'http://www.jumptags.com/add/?url=<url>&amp;title=<title>'),
array('name' => 'Kaboodle', 'icon' => 65, 'url' => 'http://www.kaboodle.com', 'share-link' => 'http://www.kaboodle.com/grab/addItemWithUrl?url=<url>&amp;pidOrRid=pid=&amp;redirectToKPage=true'),
array('name' => 'Khabbr', 'icon' => 97, 'url' => 'http://www.khabbr.com', 'share-link' => 'http://www.khabbr.com/submit.php?out=yes&amp;url=<url>'),
array('name' => 'Kledy', 'icon' => 98, 'url' => 'http://www.kledy.de', 'share-link' => 'http://www.kledy.de/submit.php?url=<url>'),
array('name' => 'Kirtsy', 'icon' => 54, 'url' => 'http://www.kirtsy.com', 'share-link' => 'http://www.kirtsy.com/submit.php?url=<url>'),
array('name' => 'Koolontheweb', 'icon' => 43, 'url' => 'http://www.koolontheweb.com', 'share-link' => 'http://www.koolontheweb.com/post?url=<url>&amp;title=<title>'),
array('name' => 'Linkarena', 'icon' => 70, 'url' => 'http://linkarena.com', 'share-link' => 'http://linkarena.com/bookmarks/addlink/?url=<url>&amp;title=<title>&amp;desc=&amp;tags='),			
array('name' => 'LinkaGoGo', 'icon' => 18, 'url' => 'http://www.linkagogo.com', 'share-link' => 'http://www.linkagogo.com/go/AddNoPopup?url=<url>&amp;title=<title>'),
array('name' => 'LinkedIn', 'icon' => 66, 'url' => 'http://www.linkedin.com', 'share-link' => 'http://www.linkedin.com/shareArticle?mini=true&amp;url=<url>&amp;title=<title>&amp;ro=false&amp;summary=&amp;source='),
array('name' => 'LiveJournal', 'icon' => 19, 'url' => 'http://www.livejournal.com', 'share-link' => 'http://www.livejournal.com/update.bml?subject=<url>'),
array('name' => 'ma.gnolia', 'icon' => 20, 'url' => 'http://ma.gnolia.com', 'share-link' => 'http://ma.gnolia.com/bookmarklet/add?url=<url>&amp;title=<title>'),
array('name' => 'Maple', 'icon' => 99, 'url' => 'http://www.maple.nu', 'share-link' => 'http://www.maple.nu/bookmarks/bookmarklet?bookmark[url]=<url>&amp;bookmark[description]=<title>'),
array('name' => 'men&eacute;ame', 'icon' => 55, 'url' => 'http://meneame.net', 'share-link' => 'http://meneame.net/submit.php?url=<url>'),
array('name' => 'MindBodyGreen', 'icon' => 21, 'url' => 'http://www.mindbodygreen.com', 'share-link' => 'http://www.mindbodygreen.com/passvote.action?u=<url>'),
array('name' => 'Mister Wong', 'icon' => 22, 'url' => 'http://www.mister-wong.com', 'share-link' => 'http://www.mister-wong.com/index.php?action=addurl&amp;bm_url=<url>&amp;bm_description=<title>'),
array('name' => 'Mixx', 'icon' => 23, 'url' => 'http://www.mixx.com', 'share-link' => 'http://www.mixx.com/submit/story?page_url=<url>&amp;title=<title>'),
array('name' => 'Multiply', 'icon' => 24, 'url' => 'http://multiply.com', 'share-link' => 'http://multiply.com/gus/journal/compose/addthis?body=&amp;url=<url>&amp;subject=<title>'),
array('name' => 'MyLinkVault', 'icon' => 100, 'url' => 'http://www.mylinkvault.com', 'share-link' => 'http://www.mylinkvault.com/link-page.php?u=<url>&amp;n=<title>'),
array('name' => 'MySpace', 'icon' => 25, 'url' => 'http://www.myspace.com', 'share-link' => 'http://www.myspace.com/Modules/PostTo/Pages/?u=<url>&amp;t=<title>'),
array('name' => 'N4G', 'icon' => 56, 'url' => 'http://www.n4g.com', 'share-link' => 'http://www.n4g.com/tips.aspx?url=<url>&amp;title=<title>'),
array('name' => 'NetLog', 'icon' => 101, 'url' => 'http://www.netlog.com', 'share-link' => 'http://www.netlog.com/go/manage/links/view=save&amp;origin=external&amp;url=<url>&amp;title=<title>'),
array('name' => 'Netscape', 'icon' => 26, 'url' => 'http://www.netscape.com', 'share-link' => 'http://www.netscape.com/submit/?U=<url>&amp;T=<title>'),
array('name' => 'Netvibes', 'icon' => 102, 'url' => 'http://www.netvibes.com', 'share-link' => 'http://www.netvibes.com/share?url=<url>&amp;title=<title>'),
array('name' => 'Netvouz', 'icon' => 27, 'url' => 'http://netvouz.com', 'share-link' => 'http://netvouz.com/action/submitBookmark?url=<url>&amp;title=<title>&amp;popup=no'),
array('name' => 'NewsTrust', 'icon' => 103, 'url' => 'http://newstrust.net', 'share-link' => 'http://newstrust.net/submit?url=<url>&amp;title=<title>&amp;ref=addtoany'),
array('name' => 'Newsvine', 'icon' => 28, 'url' => 'http://www.newsvine.com', 'share-link' => 'http://www.newsvine.com/_wine/save?u=<url>&amp;h=<title>'),
array('name' => 'NowPublic', 'icon' => 29, 'url' => 'http://view.nowpublic.com', 'share-link' => 'http://view.nowpublic.com/?src=<url>&amp;t=<title>'),
array('name' => 'OKNOtizie', 'icon' => 57, 'url' => 'http://oknotizie.alice.it', 'share-link' => 'http://oknotizie.alice.it/post?url=<url>&amp;title=<title>'),
array('name' => 'OneView', 'icon' => 72, 'url' => 'http://www.oneview.de', 'share-link' => 'http://www.oneview.de/quickadd/neu/addBookmark.jsf?URL=<url>&amp;title=<title>'),
array('name' => 'Ping', 'icon' => 104, 'url' => 'http://ping.fm', 'share-link' => 'http://ping.fm/ref/?link=<url>&amp;title=<title>'),
array('name' => 'Plaxo Pulse', 'icon' => 105, 'url' => 'http://www.plaxo.com', 'share-link' => 'http://www.plaxo.com/pulse/?share_link=<url>'),
array('name' => 'Propeller', 'icon' => 58, 'url' => 'http://www.propeller.com', 'share-link' => 'http://www.propeller.com/submit/?U=<url>&amp;T=<title>'),
array('name' => 'Protopage', 'icon' => 106, 'url' => 'http://www.protopage.com', 'share-link' => 'http://www.protopage.com/add-button-site?url=<url>&amp;label=<title>&amp;type=page'),
array('name' => 'Pusha', 'icon' => 107, 'url' => 'http://www.pusha.se', 'share-link' => 'http://www.pusha.se/posta?url=<url>'),
array('name' => 'reddit', 'icon' => 30, 'url' => 'http://reddit.com', 'share-link' => 'http://reddit.com/submit?url=<url>&amp;title=<title>'),
array('name' => 'Scoopeo', 'icon' => 46, 'url' => 'http://www.scoopeo.com', 'share-link' => 'http://www.scoopeo.com/scoop/new?newurl=<url>&amp;title=<title>'),
array('name' => 'Segnalo', 'icon' => 37, 'url' => 'http://segnalo.alice.it', 'share-link' => 'http://segnalo.alice.it/post.html.php?url=<url>&amp;title=<title>'),
array('name' => 'ShoutWire', 'icon' => 108, 'url' => 'http://www.shoutwire.com', 'share-link' => 'http://www.shoutwire.com/?s=<url>'),
array('name' => 'Simpy', 'icon' => 32, 'url' => 'http://www.simpy.com', 'share-link' => 'http://www.simpy.com/simpy/LinkAdd.do?href=<url>&amp;title=<title>'),
array('name' => 'Sitejot', 'icon' => 109, 'url' => 'http://www.sitejot.com', 'share-link' => 'http://www.sitejot.com/addform.php?iSiteAdd=<url>&amp;iSiteDes=<title>'),
array('name' => 'Slashdot', 'icon' => 33, 'url' => 'http://slashdot.org', 'share-link' => 'http://slashdot.org/bookmark.pl?url=<url>&amp;title=<title>'),
array('name' => 'SmakNews', 'icon' => 110, 'url' => 'http://smaknews.com', 'share-link' => 'http://smaknews.com/submit.php?url=<url>&amp;title=<title>'),
array('name' => 'Smarking', 'icon' => 34, 'url' => 'http://smarking.com', 'share-link' => 'http://smarking.com/editbookmark/?url=<url>&amp;title=<title>'),
array('name' => 'Sphinn', 'icon' => 44, 'url' => 'http://sphinn.com', 'share-link' => 'http://sphinn.com/submit.php?url=<url>&amp;title=<title>'),
array('name' => 'Spurl', 'icon' => 35, 'url' => 'http://www.spurl.net', 'share-link' => 'http://www.spurl.net/spurl.php?url=<url>&amp;title=<title>'),
array('name' => 'Squidoo', 'icon' => 42, 'url' => 'http://www.squidoo.com', 'share-link' => 'http://www.squidoo.com/lensmaster/bookmark?<url>&amp;title=<title>'),
array('name' => 'StartAid', 'icon' => 111, 'url' => 'http://www.startaid.com', 'share-link' => 'http://www.startaid.com/index.php?st=AddBrowserLink&amp;type=Detail&amp;v=3&amp;urlname=<url>&amp;urltitle=<title>'),
array('name' => 'Strands', 'icon' => 112, 'url' => 'http://www.strands.com', 'share-link' => 'http://www.strands.com/tools/share/webpage?url=<url>&amp;title=<title>'),
array('name' => 'StumbleUpon', 'icon' => 36, 'url' => 'http://www.stumbleupon.com', 'share-link' => 'http://www.stumbleupon.com/submit?url=<url>&amp;title=<title>'),
array('name' => 'Stumpedia', 'icon' => 113, 'url' => 'http://www.stumpedia.com', 'share-link' => 'http://www.stumpedia.com/submit?url=<url>&amp;title=<title>'),
array('name' => 'Symbaloo', 'icon' => 114, 'url' => 'http://www.symbaloo.com', 'share-link' => 'http://www.symbaloo.com/us/add/url=<url>&amp;title=<title>'),
array('name' => 'Tagza', 'icon' => 115, 'url' => 'http://www.tagza.com', 'share-link' => 'http://www.tagza.com/submit.php?url=<url>'),
array('name' => 'Tailrank', 'icon' => 37, 'url' => 'http://tailrank.com', 'share-link' => 'http://tailrank.com/share/?link_href=<url>&amp;title=<title>'),
array('name' => 'TechNet', 'icon' => 116, 'url' => 'http://social.technet.microsoft.com', 'share-link' => 'http://social.technet.microsoft.com/en-US/action/Create/s/E/?url=<url>&amp;bm=true&amp;ttl=<title>'),
array('name' => 'Technorati', 'icon' => 38, 'url' => 'http://www.technorati.com', 'share-link' => 'http://www.technorati.com/faves?add=<url>'),
array('name' => 'Technotizie', 'icon' => 117, 'url' => 'http://www.technotizie.it', 'share-link' => 'http://www.technotizie.it/posta_ok?action=f2&amp;url=<url>&amp;title=<title>'),
array('name' => 'ThisNext', 'icon' => 39, 'url' => 'http://www.thisnext.com', 'share-link' => 'http://www.thisnext.com/pick/new/submit/sociable/?url=<url>&amp;name=<title>'),
array('name' => 'Tip\'d', 'icon' => 118, 'url' => 'http://tipd.com', 'share-link' => 'http://tipd.com/submit.php?url=<url>'),
array('name' => 'tumblr', 'icon' => 119, 'url' => 'http://www.tumblr.com', 'share-link' => 'http://www.tumblr.com/share?v=3&amp;u=<url>&amp;t=<title>'),
array('name' => 'Twitter', 'icon' => 45, 'url' => 'http://www.twitter.com', 'share-link' => 'http://twitter.com/home?status=Check out <title> at <short>'),
array('name' => 'Viadeo', 'icon' => 120, 'url' => 'http://www.viadeo.com', 'share-link' => 'http://www.viadeo.com/shareit/share/?url=<url>&amp;title=<title>'),
array('name' => 'Vodpod', 'icon' => 121, 'url' => 'http://vodpod.com', 'share-link' => 'http://vodpod.com/account/add_video_page?p=<url>'),
array('name' => 'WebNews', 'icon' => 122, 'url' => 'http://www.webnews.de', 'share-link' => 'http://www.webnews.de/einstellen?url=<url>&amp;title=<title>'),
array('name' => 'Wikio', 'icon' => 47, 'url' => 'http://www.wikio.com', 'share-link' => 'http://www.wikio.com/vote?newurl=<url>'),
array('name' => 'Windows Live', 'icon' => 40, 'url' => 'http://favorites.live.com', 'share-link' => 'https://favorites.live.com/quickadd.aspx?marklet=1&amp;mkt=en-us&amp;url=<url>&amp;title=<title>'),
array('name' => 'Amazon WishList', 'icon' => 123, 'url' => 'http://www.amazon.com', 'share-link' => 'http://www.amazon.com/wishlist/add?u=<url>&amp;t=<title>'),
array('name' => 'Wists', 'icon' => 124, 'url' => 'http://wists.com', 'share-link' => 'http://wists.com/r.php?r=<url>&amp;title=<title>'),
array('name' => 'Xanga', 'icon' => 59, 'url' => 'http://www.xanga.com', 'share-link' => 'http://www.xanga.com/private/editorx.aspx?u=<url>&amp;t=<title>'),
array('name' => 'Xerpi', 'icon' => 125, 'url' => 'http://www.xerpi.com', 'share-link' => 'http://www.xerpi.com/block/add_link_from_extension?url=<url>&amp;title=<title>'),
array('name' => 'Yahoo Bookmarks', 'icon' => 60, 'url' => 'http://bookmarks.yahoo.com', 'share-link' => 'http://bookmarks.yahoo.com/toolbar/savebm?opener=tb&amp;u=<url>&amp;t=<title>'),
array('name' => 'Yahoo Buzz', 'icon' => 67, 'url' => 'http://buzz.yahoo.com', 'share-link' => 'http://buzz.yahoo.com/submit?submitUrl=<url>&amp;submitHeadline=<title>'),
array('name' => 'Yahoo MyWeb', 'icon' => 41, 'url' => 'http://myweb2.search.yahoo.com', 'share-link' => 'http://myweb2.search.yahoo.com/myresults/bookmarklet?u=<url>&amp;t=<title>'),
array('name' => 'Yardbarker', 'icon' => 68, 'url' => 'http://www.yardbarker.com', 'share-link' => 'http://www.yardbarker.com/author/new/?pUrl=<url>'),
array('name' => 'Yigg', 'icon' => 61, 'url' => 'http://www.yigg.de', 'share-link' => 'http://www.yigg.de/neu?exturl=<url>&amp;exttitle=<title>'),
array('name' => 'yoolink', 'icon' => 126, 'url' => 'http://www.yoolink.fr', 'share-link' => 'http://www.yoolink.fr/post/tag?f=aa&amp;url_value=<url>&amp;title=<title>')
);
?>